# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from statistics_manager_service.models.base_model import Model
from statistics_manager_service import util


class CO2Units(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    GCO_EQ_KWH = "gCO₂eq/kWh"
    KGCO_EQ_KWH = "KgCO₂eq/KWh"
    def __init__(self):  # noqa: E501
        """CO2Units - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CO2Units':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CO2Units of this CO2Units.  # noqa: E501
        :rtype: CO2Units
        """
        return util.deserialize_model(dikt, cls)
