from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from statistics_manager_service.models.base_model import Model
from statistics_manager_service.models.energy_units import EnergyUnits
from statistics_manager_service import util

from statistics_manager_service.models.energy_units import EnergyUnits  # noqa: E501

class EnergyTimeSeries(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timestamp=None, energy=None, units=None, slot_number=None):  # noqa: E501
        """EnergyTimeSeries - a model defined in OpenAPI

        :param timestamp: The timestamp of this EnergyTimeSeries.  # noqa: E501
        :type timestamp: datetime
        :param energy: The energy of this EnergyTimeSeries.  # noqa: E501
        :type energy: float
        :param units: The units of this EnergyTimeSeries.  # noqa: E501
        :type units: EnergyUnits
        :param slot_number: The slot_number of this EnergyTimeSeries.  # noqa: E501
        :type slot_number: float
        """
        self.openapi_types = {
            'timestamp': datetime,
            'energy': float,
            'units': EnergyUnits,
            'slot_number': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'energy': 'energy',
            'units': 'units',
            'slot_number': 'slot_number'
        }

        self._timestamp = timestamp
        self._energy = energy
        self._units = units
        self._slot_number = slot_number

    @classmethod
    def from_dict(cls, dikt) -> 'EnergyTimeSeries':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EnergyTimeSeries of this EnergyTimeSeries.  # noqa: E501
        :rtype: EnergyTimeSeries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this EnergyTimeSeries.


        :return: The timestamp of this EnergyTimeSeries.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this EnergyTimeSeries.


        :param timestamp: The timestamp of this EnergyTimeSeries.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def energy(self) -> float:
        """Gets the energy of this EnergyTimeSeries.


        :return: The energy of this EnergyTimeSeries.
        :rtype: float
        """
        return self._energy

    @energy.setter
    def energy(self, energy: float):
        """Sets the energy of this EnergyTimeSeries.


        :param energy: The energy of this EnergyTimeSeries.
        :type energy: float
        """
        if energy is not None and energy < 0:  # noqa: E501
            raise ValueError("Invalid value for `energy`, must be a value greater than or equal to `0`")  # noqa: E501

        self._energy = energy

    @property
    def units(self) -> EnergyUnits:
        """Gets the units of this EnergyTimeSeries.


        :return: The units of this EnergyTimeSeries.
        :rtype: EnergyUnits
        """
        return self._units

    @units.setter
    def units(self, units: EnergyUnits):
        """Sets the units of this EnergyTimeSeries.


        :param units: The units of this EnergyTimeSeries.
        :type units: EnergyUnits
        """

        self._units = units

    @property
    def slot_number(self) -> float:
        """Gets the slot_number of this EnergyTimeSeries.


        :return: The slot_number of this EnergyTimeSeries.
        :rtype: float
        """
        return self._slot_number

    @slot_number.setter
    def slot_number(self, slot_number: float):
        """Sets the slot_number of this EnergyTimeSeries.


        :param slot_number: The slot_number of this EnergyTimeSeries.
        :type slot_number: float
        """
        if slot_number is not None and slot_number < 1:  # noqa: E501
            raise ValueError("Invalid value for `slot_number`, must be a value greater than or equal to `1`")  # noqa: E501

        self._slot_number = slot_number
