from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from statistics_manager_service.models.base_model import Model
from statistics_manager_service.models.energy_time_series import EnergyTimeSeries
from statistics_manager_service import util

from statistics_manager_service.models.energy_time_series import EnergyTimeSeries  # noqa: E501

class ForecastVsReal(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, forecast=None, real=None):  # noqa: E501
        """ForecastVsReal - a model defined in OpenAPI

        :param user_id: The user_id of this ForecastVsReal.  # noqa: E501
        :type user_id: str
        :param forecast: The forecast of this ForecastVsReal.  # noqa: E501
        :type forecast: List[EnergyTimeSeries]
        :param real: The real of this ForecastVsReal.  # noqa: E501
        :type real: List[EnergyTimeSeries]
        """
        self.openapi_types = {
            'user_id': str,
            'forecast': List[EnergyTimeSeries],
            'real': List[EnergyTimeSeries]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'forecast': 'forecast',
            'real': 'real'
        }

        self._user_id = user_id
        self._forecast = forecast
        self._real = real

    @classmethod
    def from_dict(cls, dikt) -> 'ForecastVsReal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ForecastVsReal of this ForecastVsReal.  # noqa: E501
        :rtype: ForecastVsReal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this ForecastVsReal.


        :return: The user_id of this ForecastVsReal.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this ForecastVsReal.


        :param user_id: The user_id of this ForecastVsReal.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def forecast(self) -> List[EnergyTimeSeries]:
        """Gets the forecast of this ForecastVsReal.


        :return: The forecast of this ForecastVsReal.
        :rtype: List[EnergyTimeSeries]
        """
        return self._forecast

    @forecast.setter
    def forecast(self, forecast: List[EnergyTimeSeries]):
        """Sets the forecast of this ForecastVsReal.


        :param forecast: The forecast of this ForecastVsReal.
        :type forecast: List[EnergyTimeSeries]
        """

        self._forecast = forecast

    @property
    def real(self) -> List[EnergyTimeSeries]:
        """Gets the real of this ForecastVsReal.


        :return: The real of this ForecastVsReal.
        :rtype: List[EnergyTimeSeries]
        """
        return self._real

    @real.setter
    def real(self, real: List[EnergyTimeSeries]):
        """Sets the real of this ForecastVsReal.


        :param real: The real of this ForecastVsReal.
        :type real: List[EnergyTimeSeries]
        """
        if real is None:
            raise ValueError("Invalid value for `real`, must not be `None`")  # noqa: E501

        self._real = real
