from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from statistics_manager_service.models.base_model import Model
from statistics_manager_service.models.power_metric import PowerMetric
from statistics_manager_service import util

from statistics_manager_service.models.power_metric import PowerMetric  # noqa: E501

class PowerMetrics(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, metrics=None):  # noqa: E501
        """PowerMetrics - a model defined in OpenAPI

        :param user_id: The user_id of this PowerMetrics.  # noqa: E501
        :type user_id: str
        :param metrics: The metrics of this PowerMetrics.  # noqa: E501
        :type metrics: List[PowerMetric]
        """
        self.openapi_types = {
            'user_id': str,
            'metrics': List[PowerMetric]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'metrics': 'metrics'
        }

        self._user_id = user_id
        self._metrics = metrics

    @classmethod
    def from_dict(cls, dikt) -> 'PowerMetrics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PowerMetrics of this PowerMetrics.  # noqa: E501
        :rtype: PowerMetrics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> str:
        """Gets the user_id of this PowerMetrics.


        :return: The user_id of this PowerMetrics.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this PowerMetrics.


        :param user_id: The user_id of this PowerMetrics.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def metrics(self) -> List[PowerMetric]:
        """Gets the metrics of this PowerMetrics.


        :return: The metrics of this PowerMetrics.
        :rtype: List[PowerMetric]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics: List[PowerMetric]):
        """Sets the metrics of this PowerMetrics.


        :param metrics: The metrics of this PowerMetrics.
        :type metrics: List[PowerMetric]
        """
        if metrics is None:
            raise ValueError("Invalid value for `metrics`, must not be `None`")  # noqa: E501

        self._metrics = metrics
