from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from statistics_manager_service.models.base_model import Model
from statistics_manager_service import util


class PowerUnits(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    W = 'W'
    KW = 'kW'
    def __init__(self):  # noqa: E501
        """PowerUnits - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'PowerUnits':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PowerUnits of this PowerUnits.  # noqa: E501
        :rtype: PowerUnits
        """
        return util.deserialize_model(dikt, cls)
