from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from statistics_manager_service.models.base_model import Model
from statistics_manager_service.models.power_units import PowerUnits
from statistics_manager_service import util

from statistics_manager_service.models.power_units import PowerUnits  # noqa: E501

class PowerMetric(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timestamp=None, value=None, units=None, slot_number=None):  # noqa: E501
        """PowerMetric - a model defined in OpenAPI

        :param timestamp: The timestamp of this PowerMetric.  # noqa: E501
        :type timestamp: datetime
        :param value: The value of this PowerMetric.  # noqa: E501
        :type value: float
        :param units: The units of this PowerMetric.  # noqa: E501
        :type units: PowerUnits
        :param slot_number: The slot_number of this PowerMetric.  # noqa: E501
        :type slot_number: float
        """
        self.openapi_types = {
            'timestamp': datetime,
            'value': float,
            'units': PowerUnits,
            'slot_number': float
        }

        self.attribute_map = {
            'timestamp': 'timestamp',
            'value': 'value',
            'units': 'units',
            'slot_number': 'slot_number'
        }

        self._timestamp = timestamp
        self._value = value
        self._units = units
        self._slot_number = slot_number

    @classmethod
    def from_dict(cls, dikt) -> 'PowerMetric':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PowerMetric of this PowerMetric.  # noqa: E501
        :rtype: PowerMetric
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this PowerMetric.


        :return: The timestamp of this PowerMetric.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this PowerMetric.


        :param timestamp: The timestamp of this PowerMetric.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def value(self) -> float:
        """Gets the value of this PowerMetric.


        :return: The value of this PowerMetric.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this PowerMetric.


        :param value: The value of this PowerMetric.
        :type value: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501
        if value is not None and value < 0:  # noqa: E501
            raise ValueError("Invalid value for `value`, must be a value greater than or equal to `0`")  # noqa: E501

        self._value = value

    @property
    def units(self) -> PowerUnits:
        """Gets the units of this PowerMetric.


        :return: The units of this PowerMetric.
        :rtype: PowerUnits
        """
        return self._units

    @units.setter
    def units(self, units: PowerUnits):
        """Sets the units of this PowerMetric.


        :param units: The units of this PowerMetric.
        :type units: PowerUnits
        """
        if units is None:
            raise ValueError("Invalid value for `units`, must not be `None`")  # noqa: E501

        self._units = units

    @property
    def slot_number(self) -> float:
        """Gets the slot_number of this PowerMetric.


        :return: The slot_number of this PowerMetric.
        :rtype: float
        """
        return self._slot_number

    @slot_number.setter
    def slot_number(self, slot_number: float):
        """Sets the slot_number of this PowerMetric.


        :param slot_number: The slot_number of this PowerMetric.
        :type slot_number: float
        """
        if slot_number is None:
            raise ValueError("Invalid value for `slot_number`, must not be `None`")  # noqa: E501
        if slot_number is not None and slot_number < 1:  # noqa: E501
            raise ValueError("Invalid value for `slot_number`, must be a value greater than or equal to `1`")  # noqa: E501

        self._slot_number = slot_number
